"""add_unique_indexes

Revision ID: 08574deb3070
Revises: 791c48b50ef7
Create Date: 2020-02-29 21:37:03.519916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08574deb3070'
down_revision = '791c48b50ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'suppliers', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
